### ISSUE TITLE
[Bug]: Unused dynamic `import` still emitted

### ISSUE THREAD

**Issue by thesmartwon** [rolldown/rolldown#2699] opened 2024-11-11 18:35 UTC
### Reproduction link or steps

https://stackblitz.com/edit/github-ff4bwy?file=src%2Fhyper-cube.js

```sh
<DIR>/entry.js             chunk │ size: 0.15 kB                                                                                                                 
<DIR>/package-Vdj6VMgq.js  chunk │ size: 0.54 kB   
```

### What is expected?

No `<DIR>/package-Vdj6VMgq.js`

### What is actually happening?

`<DIR>/package-Vdj6VMgq.js`

### System Info

```Shell
Rolldown 0.14.0
```

### Any additional comments?

Ran into this while bundling https://github.com/preactjs/preact-iso/blob/d44e69b/src/index.js#L5

**Comment by hyf0** [comment] 2024-11-11 22:02
Duplicate of https://github.com/rolldown/rolldown/issues/2604.

**Closed as not planned by hyf0** 2024-11-11 22:02 UTC
Labels: bug, needs-triage
